# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Setup Custard
description: Install the Custard runner.

inputs:
  install-path:
    description: Path to install the Custard script to.
    default: custard.ts
  version:
    description: Custard version to install.
    default: v0.4.0 # x-release-please-version
  temp-dir:
    description: Temporary directory to download files.
    default: custard-temp/

runs:
  using: composite
  steps:
    - name: Install Custard
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('node:fs');
          const path = require('path');
          const contents = await github.request('GET /repos/{owner}/{repo}/contents/{path}', {
            owner: 'GoogleCloudPlatform',
            repo: 'cloud-samples-tools',
            path: 'scripts/src/custard.ts',
            ref: '${{ inputs.version }}',
            headers: {
              accept: 'application/vnd.github.raw+json',
              'X-GitHub-Api-Version': '2022-11-28',
            },
          });
          const filename = "${{ inputs.install-path }}";
          fs.mkdirSync(path.dirname(filename), { recursive: true });
          fs.writeFileSync(filename, contents.data);

    # Node is available in the default github runner, but at an order version
    # that does not support TS by default. So, update the Node version used here.
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - run: node ${{ inputs.install-path }} version
      shell: bash
