# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: workflows

on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - actions/**
      - custard/**
  pull_request:
    paths:
      - .github/**
      - actions/**
      - custard/**
  workflow_run:
    workflows:
      - Custard CI # .github/workflows/custard-ci.yaml
    types:
      # There's no need to wait for the "submit job" to finish.
      # As long as it's "in_progress", it means it has been approved.
      - in_progress
  workflow_dispatch:
    inputs:
      run-all:
        description: Run all tests
        type: boolean
        default: false
      paths:
        description: Comma separated packages to test
        type: string
      ref:
        description: Branch, tag, or commit SHA to run tests on
        type: string
        default: origin/main

jobs:
  github-context:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      # For debugging information.
      - run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: echo "$INPUTS"
        env:
          INPUTS: ${{ toJson(inputs) }}

  affected:
    uses: ./.github/workflows/affected.yaml
    permissions:
      statuses: write
    with:
      head-sha: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha || inputs.ref || github.sha }}
      config-file: .github/test/config.jsonc
      paths: ${{ (inputs.run-all && '.') || inputs.paths || '.github/test/pkg1' }}
      create-check-if: ${{ !!github.event.workflow_run || (github.event.pull_request && !github.event.pull_request.head.repo.fork) }}
      check-name: Custard CI (create-check)
      timeout-minutes: 1

  setup-custard:
    needs: affected
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.affected.outputs.paths) }}
    continue-on-error: true
    timeout-minutes: 1
    steps:
      - name: Check queued
        uses: GoogleCloudPlatform/cloud-samples-tools/actions/steps/create-check@v0.2.4
        id: queued
        with:
          sha: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha || inputs.ref || github.sha }}
          name: workflows / ${{ github.job }} (${{ matrix.path }}) (create-check)
          job-name: ${{ github.job }} (${{ matrix.path }})
          if: ${{ !!github.event.workflow_run || (github.event.pull_request && !github.event.pull_request.head.repo.fork) }}
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha || inputs.ref || github.sha }}
      - name: Setup Custard
        uses: GoogleCloudPlatform/cloud-samples-tools/actions/steps/setup-custard@57945e1e95917407558192c975ccc1e1f1e7a0e7
        with:
          path: ${{ matrix.path }}
          ci-setup: ${{ toJson(fromJson(needs.affected.outputs.ci-setups)[matrix.path]) }}
          project-id: my-project
      - name: Check in_progress
        uses: GoogleCloudPlatform/cloud-samples-tools/actions/steps/update-check@v0.2.4
        id: in_progress
        with:
          check: ${{ steps.queued.outputs.check }}
          status: in_progress
      - run: bash run.sh
        shell: bash
        working-directory: ${{ matrix.path }}
      - name: Check success
        uses: GoogleCloudPlatform/cloud-samples-tools/actions/steps/update-check@v0.2.4
        with:
          check: ${{ steps.in_progress.outputs.check }}
          status: success
      - name: Check failure
        uses: GoogleCloudPlatform/cloud-samples-tools/actions/steps/update-check@v0.2.4
        if: failure()
        with:
          check: ${{ steps.in_progress.outputs.check }}
          status: failure

  done:
    needs: [affected, setup-custard]
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    timeout-minutes: 1
    steps:
      - name: Check success
        uses: GoogleCloudPlatform/cloud-samples-tools/actions/steps/update-check@v0.2.4
        with:
          check: ${{ needs.affected.outputs.check }}
          status: success

  map-run:
    needs: affected
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    timeout-minutes: 1
    steps:
      - name: Check in_progress
        uses: GoogleCloudPlatform/cloud-samples-tools/actions/steps/create-check@v0.2.4
        id: in_progress
        with:
          sha: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha || inputs.ref || github.sha }}
          status: in_progress
          name: workflows / ${{ github.job }} (create-check)
          if: ${{ !!github.event.workflow_run || (github.event.pull_request && !github.event.pull_request.head.repo.fork) }}
      - name: Checkout Custard
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run command on affected paths
        uses: GoogleCloudPlatform/cloud-samples-tools/actions/steps/map-run@v0.2.4
        with:
          command: ls -lh
          paths: ${{ needs.affected.outputs.paths }}
          outputs-always: true
      - name: Check success
        uses: GoogleCloudPlatform/cloud-samples-tools/actions/steps/update-check@v0.2.4
        with:
          check: ${{ steps.in_progress.outputs.check }}
          status: success
      - name: Check failure
        uses: GoogleCloudPlatform/cloud-samples-tools/actions/steps/update-check@v0.2.4
        if: failure()
        with:
          check: ${{ steps.in_progress.outputs.check }}
          status: failure
